on:
  push: 
    tags: 
      - '*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-to: |
            type=gha,mode=max,scope=${{ github.ref_name }}
          cache-from: |
            type=gha,scope=main
            type=gha,scope=${{ github.ref_name }}
          tags: |
            cowboygneox/playdate-ci:${{ github.ref_name }}
            cowboygneox/playdate-ci:latest

      - name: Run the build process with Docker
        run: |
          docker run --rm cowboygneox/playdate-ci:latest
